# Generated by Django 5.2 on 2025-04-10 16:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_remove_post_tags_comentario_resposta_a'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensagem',
            name='resposta_a',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='blog.mensagem'),
        ),
    ]
